import Foundation

// The whole suite, run as an ordinary executable. See Harness.swift for why this is not XCTest.
runNoteFilenameTests()
runNoteNamingTests()
runMarkdownDocumentTests()
runNoteTitleCorpusTests()
runNoteOrderingTests()
runNoteIndexTests()
runPanelGeometryTests()
runPaneWidthTests()
runStateTests()
runSettingsTests()
runSummonPolicyTests()
runVaultSyncTests()
runVaultIOTests()
runRecentlyDeletedTests()
runMarkdownExportTests()
runAutoSizingTests()
runReleaseCheckTests()
runLinkTargetTests()
runBuildProfileTests()
runWelcomeNoteTests()

exit(Check.finish())
